import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { Quicksand, Cormorant_Garamond } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const quicksand = Quicksand({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-quicksand",
});

export const leagueGothic = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-league-gothic",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${quicksand.variable} ${leagueGothic.variable}`}
    >
      <body className={`bg-bluegray-500 font-sans`}>
        <div className="flex justify-center items-center gap-8">
          <Link href="/">Home</Link>
          <Link href="/tarefa1">Olá</Link>
          <Link href="/tarefa2">Calculadora</Link>
          <Link href="/tarefa3">Arquitetura</Link>
          <Link href="/tarefa4">Biblioteca</Link>
          <Link href="/tarefa5">Programação</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
